config/routes.rb
Rubydama01::Application.routes.draw do

  root :to => "media#show"

  #get "run" => 'media#run'

#  post ":id/create" => "media#create", :constraints => { :id => /[a-zA-Z0-9_\-]+/ }, :as => "create_media"
  resources :media,
            :path => '',
            :only => [:show, :edit, :update],
            :constraints => { :id => /[a-zA-Z0-9_\-]+/ } do
    member do
#      post :new
      get :talk
      post :create
    end
#    collection do
#     post :create
#    end
  end

  get ":context/:id" => "media#show",
       :constraints => { :context => /[a-zA-Z0-9_\-]+/, :id => /[a-zA-Z0-9_\-]+/ }

end

app/models/media.rb
class Media < ActiveRecord::Base
  include Url
  include InitMedia
  belongs_to :data, :polymorphic => true
  belongs_to :mediatype, :class_name => "Media"
  validates :title,
   :presence => true,
   :length => {:minimum => 1}
  before_create do |media|
    media.title.capitalize! if media.data_type == "Mediatype"
  end
  after_create do |media|
    media.url = encode media.id
    media.mediatype.count += 1
    media.save
    media.mediatype.save
  end
  before_save do |media|
    init_obj( media.data_type ) unless Object.const_defined? media.data_type
    media.mediatype.data.arguments.each do |w|
      media.data.send(w.keys[0]).delete_if {|x| x.empty? }.map! {|x| x.map {|y| {y[0]=>y[1]} } }.flatten! if w.values[0].downcase=="array"
      #media.data.send(w.keys[0]).compact.inject(:"merge!") if w.values[0].downcase=="hash"
    end
  end
end

class Mediatype < ActiveRecord::Base
  include InitMedia
  has_many :media, :as => :data, :dependent => :destroy #has_one
  serialize :arguments, Array
  serialize :views, Array
  after_create "save_table('create')"
  after_update "save_table('alter')"
  protected
  def save_table(action) #separate
    init_obj(media[0].title) unless Object.const_defined? media[0].title
    basetype = {"Array" => "Text", "Hash" => "Text"}
    T.send(
      action,
      media[0].title.downcase.pluralize.to_sym,
      arguments.delete_if {|x| x.empty? }.map {|x| x.map {|y| { y[0] => (basetype[y[1]] || y[1]) } } }.flatten.inject({}) {|x,y| x.merge(y) }
    )
  end
end

class Editor < ActiveRecord::Base
  has_many :media, :as => :data, :dependent => :destroy #has_one
#has_one :mediatype #rename mtype ..?
  serialize :forms, Array
  serialize :views, Array
end

app/models/media_sweeper.rb
class MediaSweeper < ActionController::Caching::Sweeper
  observe Media

  def after_update(media)
    Media.where("mediatype_id = ?", media.id).each do |instance|
      expire_page(/\/#{instance.url}\/[^\/]*/)
#      expire_page("/" + instance.url, :id => /.*/)
    end
    expire_page("/" + media.url)
puts Rails.cache.instance_variables.to_s
expire_page("/b/c")
  end
end

app/models/mediatype_resolver.rb
class MediatypeResolver < ActionView::PathResolver

  #views["x"] is for converting media to x format
  #views["x:y"] is an included file of mediatype x - may be for internal use only

  include Url

  def find_templates(name, prefix, partial, details)
    name.sub!(/\A([^\?]*)(\?.*)\Z/,'\1')
    name.sub!(/\A(?:.+:)?(.+)\.(.+)\Z/, '\2:\1') unless name.index(".").nil?
    mediatype, name = name.index(":").nil? ? ["", name] : name.split(":")
    if partial or mediatype.downcase == "partial"
      partial = true
      mediatype = "partial"
    end
    path = MediaPath.build(name, prefix, partial, mediatype.empty? ? details[:formats] : [mediatype.to_sym])
    query(path, details, path.formats )
  end

  def query(path, details, formats)
    p = path.split("/")
    mediatype = p[-1].index(":").nil? || !p[0].index("partial:").nil? ?
      Media.find( decode p[0].sub(/^.+:/,"") ).mediatype :
      Media.find( decode p[0].sub(/^.+:/,"") )
    name = ( [formats.first] + [p[-1].sub(/^.+:/,"")].reject {|y| p[-1].index(":").nil? or p[-1].split(":")[-1] == p[0].split(":")[-1] } ) * ":"
    mediatype.data.views.select { |x| x.keys[0] == name }.map { |hash|
      ActionView::Template.new(hash.values[0], path, ActionView::Template::Handlers::ERB,
        :virtual_path => path.virtual,
        :format       => formats.first, #???
        :updated_at   => mediatype.updated_at) #<- for each template?
    }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_cache_buster
  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "0"
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController

  append_view_path MediatypeResolver.new

  cache_sweeper :media_sweeper

  include Url
  include InitMedia

  def show
    params[ :id ] = "i" if params[ :id ].nil? #Frontpage.find(1).media[0].url
    request.fullpath[ 1 ] = "i" if request.fullpath == "/"
    if params[ :context ].nil?
      media = Media.find( decode params[:id] )
      instance_variable_set( "@" + media.data_type.downcase, media )
      new if ( @_mediatype = media.data_type ) == "Editor"
      init_obj( @_mediatype ) unless Object.const_defined? @_mediatype
      render request.fullpath, :layout => (
        ( [ "Mediatype", "Editor", "Frontpage" ].include? @_mediatype and
          [ "html", nil ].include? params[ :format ] ) ?
        "application" :
        false
      ) #layouts are partials!
    else
      @_media = Media.find ( decode params[ :context ] )
      if request.fullpath.index( "." ).nil?
        ( @_mediatype = @_media.data_type ) == "Editor" ?
        edit :
        redirect_to(
          "/" + Editor.where( :mtype => @_media.mediatype.id )[ 0 ].media[ 0 ].url + "/" + params[ :id ]
        )
      else
        render request.fullpath[ 1..-1 ], :layout => false
      end
    end
  end

  def edit
    @_media = Media.find( decode params[ :id ] )
    init_obj( @_media.data_type ) unless Object.const_defined? @_media.data_type
    editors = Editor.where( :mtype => @_media.mediatype.id )
    if params[ :context ].nil?
      editors.length > 0 ?
      redirect_to( "/" + editors[ 0 ].media[ 0 ].url + "/" + params[ :id ] ) :
      redirect_to( "/" + encode( 4 ) ) #Editor.where(:mtype => Media.where(:title => "Editor").id).url
    else
      @_editor = Media.find( decode params[ :context ] )
      if @_editor.data.mtype == @_media.mediatype_id
#Rails.cache.expire(request.fullpath) if stale?(:last_modified => @_editor.updated_at.utc, :etag => @_editor)
        instance_variable_set( "@" + @_media.data_type.downcase, @_media )
        init_obj( "Editor" ) unless Object.const_defined? "Editor"
        response.headers[ "X-XSS-Protection" ] = "0" #This means we are obliged to do it ourselves
#fresh_when(@_editor) || render(request.fullpath[1..-1], :layout => "application")
        render( request.fullpath[ 1..-1 ], :layout => "application" )
      else
        redirect_to( "/" + editors[ 0 ].media[ 0 ].url + "/" + params[ :id ] ) #preferences?
      end
    end
  end

  def update
    media = Media.update( decode( params[ :id ] ), params[ :media ] )
#    init_obj( media.data_type ) unless Object.const_defined? media.data_type
    media.data = Object.const_get( media.data_type ).update(
      media.data_id,
      params[ media.data_type.downcase.to_sym ]
    )
    media.save
    media.data.save
    redirect_to :back
  end

  def new #add :mediatype/new route later
    @_editor = Media.find( decode params[ :id ] )
    mediatype = Media.find( @_editor.data.mtype )
    @_media = instance_variable_set( "@" + mediatype.title.downcase, Media.new(
      :title => "New " + mediatype.title.downcase,
      :info => "It's a new " + mediatype.title.downcase + "!",
      :url => ""
    ) )
    @_media.mediatype = mediatype
    init_obj( mediatype.title ) unless Object.const_defined? mediatype.title
    @_media.data = Object.const_get( mediatype.title ).new
  end

  def create
    return show if params[:formats].include? :api or (editor = Media.find( decode params[ :id ] )).data_type == "Api"
    media = Media.new( params[:media] )
    media.mediatype_id = editor.data.mtype
    init_obj( media.mediatype.title ) unless Object.const_defined? media.mediatype.title
    media.data = Object.const_get( media.mediatype.title ).new(
      params[ media.mediatype.title.downcase.to_sym ]
    )
    editor.count += 1
    editor.save
    media.data.media[ 0 ] = media
    media.save
    media.data.save
    redirect_to media_url + "/" + media.url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_mediatype.html.erb
<%
 tt = mediatype.title.downcase
 @title = "All " + tt.pluralize + " | kotoda.ma"
 media = instance_variable_get("@" + tt.pluralize)
 mt = Media.where("title = ?", mediatype.mtype)[0]
 e = Media.find(Editors.where("mtype = ?", mt.id)[0].media_id)
%>
<table id="<%= tt %>_page" class="page">
 <tr>

  <td id="<%= tt %>_content" class="left">
   <span class="page_title">'<%= tt.capitalize %>' mediatype summary</span>

   <table id="page_type" mediatype="mediatype">
    <tr>
     <td id="page_type_thumb" class="thumb" rowspan="3"><a href="example.html">Thumbnail</a></td>
     <td id="page_type_title" class="data">
      <%= link_to "New " + tt, tt.url %>
      <%= link_to mediatype.author, "userpage.html" %>
      <span><%= media.count.to_s + " instance" + (media.count==1 ? "" : "s") %></span>
     </td>
    </tr>
    <tr>
    <td id="page_desc" colspan="2">
     <span>Description</span>
     <span>(<%= link_to mediatype.mtype, mt.url %>)</span>
    </td>
    </tr>
    <tr>
     <td class="actions" colspan="2">
      <a href="discussion.html">Discussion</a>
      <span class="view">
       <%= link_to "View in ' + mediatype.mtype.downcase + ' editor", e.url %>
      </span>
     </td>
    </tr>
   </table>


   <table style="margin-bottom:15px">
    <tr>
     <td id="page_title" class="data">
      <%= link_to "New " + tt, root_url + tt.url %>
      <span><%= media.count.to_s + " instance" + (media.count==1 ? "" : "s") %></span>
     </td>
     <td class="actions">
      <%= link_to "Discussion", talk_media_path(@media.url) %>
     </td>
    </tr>
   </table>
   <div class="canvas" mediatype="mediatype"><%= render :partial => "home/summary", :collection => media %></div>
  </td>

  <td id="ads" class="right">
   <table class="ad">
    <tr>
     <td>
      <div class="ad_image">
       <div class="dummy_ad">
        <a href="ad.html"><img style="width:55px;height:40px" src="media/kotodama_logo_2.png"/></a>
       </div>
      </div>
     </td>
    </tr>
    <tr>
     <td><a href="ad.html">Want ad space?</a></td>
    </tr>
   </table>
  </td>

 </tr>
</table>

app/views/home/editor.html.erb
<%-
 mt = @_media.data_type.downcase
 @title = "Edit " + ((@_media.url!="")?mt + " '" + @_media.title + "'":"new " + mt)
 @_editor.forms << {"Render"=>"<iframe id=\"render\" class=\"editor_window\"></iframe>"}
-%>
<% content_for :head do %>
<script type="text/javascript">
function toggle_frames(it) {
 for (i in eddisp.frames) if ($(eddisp.frames[i]).style.display!=="none") break;
 if (eddisp.menu[i]==it) return false;
 $(eddisp.frames[i]).style.display="none";
 $(eddisp.frames[j=eddisp.menu.indexOf(it)]).style.display=eddisp.display[j];
 if (eddisp.finalfunc) eddisp.finalfunc(it);
 return eddisp.frames[i];
}
var eddisp={
 frames:<%= @_editor.forms.map {|x| x.keys[0].downcase + "_frame" }.to_s.html_safe %>,
 display:<%= @_editor.forms.map {|x| "block" }.to_s.html_safe %>,
 menu:<%= @_editor.forms.map {|x| x.keys[0] }.to_s.html_safe %>
}
</script>
<%= render :inline => @_editor.script %>
<style type="text/css">
#menu_bar {
 float:right
}
#canvas>* {
 height:100%
}
.page {
 margin-bottom:0px
}
.bottom {
 padding:5px
}
.dropdown {
 display:none
}
form {
 display:table
}
form>div {
 display:table-row
}
.interface,.top,.bottom {
 display:table-cell;
 padding:5px
}
</style><%-
 end

 content_for :onload do
-%> document.documentElement.className="noscroll";
 for (j in eddisp.frames) $(eddisp.frames[j]).style.display="none";
 $(eddisp.frames[j]).style.display=eddisp.display[j];
 //eddisp.finalfunc(eddisp.menu[j]);
 $("render").src = window.location.href.replace(/^.*\//, '/')<%-
 end
-%>
<%= render "home/login" %>
<%= form_for instance_variable_get("@" + mt), :url => {:action => @action}, :html => {:class => "page"} do |p|%>
<div><%= render "home/interface" %></div>
 <div>
  <div id="editor_actions" class="top">
   <span class="section_title"
    ><%= link_to mt.capitalize, root_url + @_mediatype.url %>: <%= link_to @_media.title, root_url + @_media.url, :id => "title", :onmousedown => "if (event.which===1) stringedit(this,true);return false" %><%= p.text_field :title, :class=>"hide", :onkeypress=>"if (event.which===13) stringedit(this,false)", :onblur=>"if (this.style.display!=='none') stringedit(this,false)" %>
   </span>
   <span class="section_info">
    <span onclick="textedit(this,true)">Info</span
    ><div class="dropdown">
<%= p.text_area :info, :onkeypress => "if (event.which===13&&!event.shiftKey) {textedit(this.parentNode,false);return false}", :onblur => "if ((p=this.parentNode).style.display!=='none') textedit(p,false)" %></div>
   </span>
   <div id="menu_bar" class="actions">
    <a href="#" onclick="document.forms[1].submit()">Save</a>
    <%= link_to "New", root_url + @_editor.media[0].url %>
    <%- @_editor.forms.each do |f| -%><a href="#" onclick="toggle_frames(this.firstChild.data)"><%= f.keys[0] %></a><%- end -%>
   </div>
<%- @_mediatype.data.arguments.select {|x| x.values[0] == "Array" }.each do |f| -%>
   <div id="<%= f.keys[0].downcase.singularize %>_operations" class="actions">
    <a href="#" onclick="ins.call($('<%= f.keys[0].downcase %>_container'))">Insert</a>
    <a href="#" onclick="del.call($('<%= f.keys[0].downcase %>_container'))">Delete</a>
    <a href="#">Move</a>
   </div>
<%- end -%>
  </div>
 </div>
 <div>
  <div id="canvas" class="bottom"><%= fields_for instance_variable_get("@" + mt).data do |data| %>
   <%= render :partial => "home/frame", :collection => @_editor.forms, :locals => {:data => data} %>
  <%- end -%></div>
 </div>
<%- end -%>

app/views/home/mediatype.html.erb
<%-
 tt = @mediatype.title.downcase
 @title = "All " + tt.pluralize
 media = instance_variable_get("@" + tt.pluralize)
 mt = Media.where("title = ?", @mediatype.data_type)[0]
 e = Editor.where(:mtype => mt.id)[0].media

 content_for :head do
-%><script type="text/javascript">
var editor={
 mediatype:{Editmediatype:"/b"},
 <%= tt %>:{<%= Editor.where(:mtype => @mediatype.id).map do |ee|
 ee.media[0].title + ":\"/" + ee.media[0].url + "\""
end[0].html_safe %>}
};
</script><%-
 end

 content_for :onload do
  -%> var i,views=document.getElementsByClassName("view");
 for (i=0;i<views.length;i++) views[i].onmousedown=viewlinks;<%-
 end -%>
<table id="<%= tt %>_page" class="page">
 <tr>

  <td id="<%= tt %>_content" class="left">
   <span class="page_title">'<%= tt.capitalize %>' mediatype summary</span>

   <table id="<%= tt %>_type" mediatype="<%= mt.title.downcase %>">
    <tr>
     <td id="<%= tt %>_type_thumb" class="thumb" rowspan="3"><a href="example.html">Thumbnail</a></td>
     <td id="<%= tt %>_type_title" class="data">
      <%= link_to "New " + tt, root_url %>
      <%= link_to @mediatype.author, "userpage.html" %>
      <span><%= @mediatype.count.to_s + " instance" + (@mediatype.count==1 ? "" : "s") %></span>
     </td>
    </tr>
    <tr>
    <td id="<%= tt %>_desc" colspan="2">
     <span><%= @mediatype.info %></span>
     <span>(<%= link_to mt.title, mt.url %>)</span>
    </td>
    </tr>
    <tr>
     <td class="actions" colspan="2">
      <%= link_to "Discussion", talk_media_url(@mediatype.url) %>
      <span class="view">
       <%= link_to "View in " + mt.title.downcase + " editor", edit_media_url(@mediatype.url) %>
      </span>
     </td>
    </tr>
   </table>
   <div class="canvas" mediatype="<%= tt %>"><%= render :partial => "home/summary", :collection => media %></div>
  </td>

  <td id="ads" class="right">
   <table class="ad">
    <tr>
     <td>
      <div class="ad_image">
       <div class="dummy_ad">
        <a href="ad.html"><img style="width:55px;height:40px" src="media/kotodama_logo_2.png"/></a>
       </div>
      </div>
     </td>
    </tr>
    <tr>
     <td><a href="ad.html">Want ad space?</a></td>
    </tr>
   </table>
  </td>

 </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-AU" mediatype="<%= @_mediatype.downcase %>">
<head>
<title><%= @_title %> | kotoda.ma</title>
<%= stylesheet_link_tag :common, :media => "all" %>
<%= javascript_include_tag :common %>
<%= favicon_link_tag %>
<%= csrf_meta_tags %>
<%= yield :head %>
<script type="text/javascript">
// body onload:
function init() {
 render_login();
<%= yield :onload %>
}
</script>
</head>
<body onload="init()">
<%= yield %>
</body>
</html>

app/views/pages/index.html.erb
<table id="show" class="page">
 <tr>

  <td id="show_pages" class="left">
   <span class="page_title">'Page' mediatype summary</span>
   <table id="page_type" mediatype="mediatype">
    <tr>
     <td id="page_type_thumb" class="thumb" rowspan="3"><a href="example.html">Thumbnail</a></td>
     <td id="page_type_title" class="data">
      <a href="pages/new">Pages</a>
      <a href="userpage.html">kotoda.ma</a>
      <span><%= @pages.count %> instances</span>
     </td>
    </tr>
    <tr>
    <td id="page_desc" colspan="2">
     <span>Description</span>
     <span>(<%= link_to "Mediatype", root_url + "a" %>)</span>
    </td>
    </tr>
    <tr>
     <td class="actions" colspan="2">
      <a href="discussion.html">Discussion</a>
      <span class="view">
       <%= link_to "View in mediatype editor", root_url + "b" %>
      </span>
     </td>
    </tr>
   </table>

   <div class="canvas" mediatype="page"><%= render @pages %></div>

  </td>

  <td id="ads" class="right">
   <table class="ad">
    <tr>
     <td>
      <div class="ad_image">
       <div class="dummy_ad">
        <a href="ad.html"><img style="width:55px;height:40px" src="media/kotodama_logo_2.png"/></a>
       </div>
      </div>
     </td>
    </tr>
    <tr>
     <td><a href="ad.html">Want ad space?</a></td>
    </tr>
   </table>
  </td>

 </tr>
</table>

app/views/talk/talk.html.erb
<% content_for :head do -%>
<script type="text/javascript">
function toggle_reply(here) {
 a=$("reply_form_"+here).style.display;
 $("reply_form_"+here).style.display=a?"":"block";
 $("reply_"+here).style.display=a?"":"none"
}
</script>
<style type="text/css">
#page {
 margin-bottom:20px
}
#discussion_canvas {
 border-top:1px solid black;
 padding-top:10px
}
#discussion_canvas>div {
 margin-left:0px
}
</style>
<%- end -%>
<!--Discussion section-->
  <table id="discussion_page" class="page">
   <tr>
    <td id="discussion_content" class="left">
     <span class="page_title">Discussion</span>
<%= render @page %>

   <!--Discussion comments section-->
     <div id="discussion_canvas" mediatype="comment">

      <div id="comment_1" class="comment_box">
       <table class="comment">
        <tr>
         <td class="data">
          <span>259 <a href="#">&#x2195;</a></span>
          <a href="userpage.html">Aidan</a>
          <span>3 days ago</span>
        </tr>
        <tr>
         <td>
          <span>Example comment</span>
         </td>
        </tr>
       </table>
       <div id="actions_1" class="actions_left">
        &#x25cb;&ensp;<a href="#" id="reply_1" onclick="toggle_reply(1)">Reply</a>
        <a href="comment.html">Permalink</a>
       </div>
       <form id="reply_form_1" class="reply_form">
        <textarea></textarea><br/>
        <a href="#" onclick="toggle_reply(1)">Submit</a>
        <a href="#" onclick="toggle_reply(1)">Cancel</a>
       </form>

       <div id="comment_2" class="comment_box">
        <table class="comment">
         <tr>
          <td class="data">
           <span>37 <a href="#">&#x2195;</a></span>
           <a href="userpage.html">Author</a>
           <span>Time</span>
          </td>
         </tr>
         <tr>
          <td>
           <span>Nested comment</span>
          </td>
         </tr>
        </table>
        <div id="actions_2" class="actions_left">
         &#x25cb;&ensp;<a href="#" id="reply_2" onclick="toggle_reply(2)">Reply</a>
         <a href="comment.html">Permalink</a>
        </div>
        <form id="reply_form_2" class="reply_form">
         <textarea></textarea><br/>
         <a href="#" onclick="toggle_reply(2)">Submit</a>
         <a href="#" onclick="toggle_reply(2)">Cancel</a>
        </form>
       </div>

      </div>

      <div id="comment_3" class="comment_box">
       <table class="comment">
        <tr>
         <td class="data">
          <span>191 <a href="#">&#x2195;</a></span>
          <a href="userpage.html">Author</a>
          <span>Time</span>
         </td>
        </tr>
        <tr>
         <td>
          <span>Comment</span>
         </td>
        </tr>
       </table>
       <div id="actions_3" class="actions_left">
        &#x25cb;&ensp;<a href="#" id="reply_3" onclick="toggle_reply(3)">Reply</a>
        <a href="comment.html">Permalink</a>
       </div>
       <form id="reply_form_3" class="reply_form">
        <textarea></textarea><br/>
        <a href="#" onclick="toggle_reply(3)">Submit</a>
        <a href="#" onclick="toggle_reply(3)">Cancel</a>
       </form>
      </div>

     </div>
   <!--end section-->

    </td>

    <td id="ads" class="right">
     <table class="ad">
      <tr>
       <td>
        <div class="ad_image">
         <div class="dummy_ad">
<%= link_to image_tag("kotodama_logo_2.png",:style=>"width:55px;height:40px"), "ad.html" %>
         </div>
        </div>
       </td>
      </tr>
      <tr>
       <td><a href="ad.html">Want ad space?</a></td>
      </tr>
     </table>
    </td>

   </tr>
  </table>